### ISSUE TITLE
 "Visualization_leaflet.R" not found

### ISSUE THREAD

**Issue by Jasonliu21** [ludvigla/STUtility_web_site#2]
devtools::install_github("jbergenstrahle/STUtility")
Downloading GitHub repo jbergenstrahle/STUtility@HEAD
✓  checking for file ‘/tmp/RtmpRe8jqn/remotes7a8c1bb1158f/jbergenstrahle-STUtility-f06ee5a/DESCRIPTION’ ...
─  preparing ‘STutility’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘STutility_0.1.0.tar.gz’
   
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘STutility’ ...
** using staged installation
** R
Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from '/tmp/Rtmph10yBn/R.INSTALL7b8727fb79be/STutility/R':
  Visualization_leaflet.R
ERROR: unable to collate and parse R files for package ‘STutility’
* removing ‘/usr/local/lib/R/site-library/STutility’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpRe8jqn/file7a8c340936e9/STutility_0.1.0.tar.gz’ had non-zero exit status

**Comment by ludvigla** [comment]
Thanks for the report. Test if it works now!

Best,
Ludvig

**Comment by Jasonliu21** [comment]
@ludvigla  Tt works! And thank you for the quick reply.
