### ISSUE TITLE
Difference between 1k vs 2k platform

### ISSUE THREAD

**Issue by ZheFrench** [ludvigla/STUtility_web_site#4]
Hi,
Except the number of spots, what the difference between 1k vs 2k platform ? 
It's just different rownames / colnames convention ? 
Do you have a set of examples (or references that pinpoint these2 platforms) ?
I will work with the dataset from [Her2](https://github.com/almaan/her2st/) and i was wondering If I could detect the type of platform directly by looking colnames/rownames.
Thank you.

**Comment by ludvigla** [comment]
Hi there,
The number of spots really is the only major difference between the 1k and 2k platforms. The 1k spots are arranged into regular grid while the 2k spots are arranged more in a "diamond" pattern. It is more densely packed, so the center-to-center distance is of course slightly shorter. Other than that, the spot diameter is the same so the number of cells per spot should be more or less the same in 1k and 2k data.
We didn't have a strict naming convention for these two platforms, but the most common one you'll find is just XxY where X, Y are the grid coordinates on the array. This is what you'll find in the HER2 dataset which is btw 1k platform data. You might also come across something like XxY_N where a section number has been appended to the coordinates.

I think the easiest way to check is to look at the arrangement of spots: regular grid vs. "diamond". You can also download the raw count matrices and just check the total number of spots which should be close to 1,000 for 1k and 2,000 for 2k.

Best,
Ludvig
